### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by odscjen** [GFDRR/rdls-cove#16] opened 2023-08-25 12:39 UTC
From the scoping document:

"A name that reflects the purpose of the tool."

What should the tool be named? Similar tools for other data standards are named ‘Data Review Tool’, ‘Data Quality Tool’ and ‘Convert, Validate, Explore Tool (CoVE)’.

**Comment by odscjen** [comment] 2023-08-25 12:40
"Risk Data Library metadata toolkit" agreed in the doc

**Comment by stufraser1** [comment] 2023-08-29 08:41
@pzwsk are you also happy with "Risk Data Library Standard metadata toolkit"? as used currently: 
![image](https://github.com/GFDRR/rdls-cove/assets/12515042/98ccdce1-2113-4bbd-9c65-147c749a9ca2)

We should agree today if possible.

**Comment by duncandewhurst** [comment] 2023-09-01 02:19
Contrary to my comment in the scoping document, if you think that you'll likely add other tools to the toolkit in the future, I suggest that we choose a different name for CoVE so that we don't then have to rename it or redesign the landing page once other tools exist.

**Comment by stufraser1** [comment] 2023-09-01 07:07
I had a niggling concern about that too...so how about, since conversion and validation is too much for a name, and it creates JSON files a number of ways, and I don't think cove describes enough what it does:
RDLS JSON creator
RDLS JSON writer
RDLS JSON convertor

**Comment by odscjen** [comment] 2023-09-01 08:19
CoVE does two things primarily, validation and conversion. If this is too long a name then I'd recommend picking the element that you think your users are most likely to be using it for. In previous conversations you've indicated that most users will want to use the spreadsheet template to create their RDLS so I think "RDLS JSON convertor" is the better option as it emphasises the element of the tool that most users will be looking for.

**Comment by stufraser1** [comment] 2023-09-01 16:40
@pzwsk and I spoke and confirmed we would like to go ahead with:
RDLS Convertor

With a subtitle or main heading in the tool of "Convert and validate RDLS metdata"

**Comment by radix0000** [comment] 2023-09-04 07:16
This is now done. Should I go through the text on the front page and make it more in line with the idea that most users will be primarily thinking about converting their metadata to JSON and the validation is secondary e.g.
"Use one of the links below to check that your data complies ..." -> "Use one of the links below to convert
your metadata and check that it complies ..."?

**Comment by duncandewhurst** [comment] 2023-09-04 22:11
@radix0000 yep, good spot. I've done that in the updates suggested in https://github.com/GFDRR/rdls-cove/issues/21#issuecomment-1705727975.

There is a typo in the header (metdata -> metadata), but in any case I would update the header as follows to reduce repetition:

![image](https://github.com/GFDRR/rdls-cove/assets/19265814/076e3490-bdc4-479f-b5f2-9a977a1261ec)

**Comment by duncandewhurst** [comment] 2023-09-05 08:12
From today's check-in call:

Above the line: Risk Data Library Standard Convertor
Below the line: Convert and validate your RDLS metadata

Remove 'Convert and validate your RDLS metadata' heading from the first box.

**Comment by radix0000** [comment] 2023-09-05 09:29
Fix header

**Comment by radix0000** [comment] 2023-09-05 15:51
Done.

**Comment by duncandewhurst** [comment] 2023-09-05 20:15
The below the line text is missing 'RDLS' before 'metadata':

![image](https://github.com/GFDRR/rdls-cove/assets/19265814/337f98b8-ec5f-47ee-bdb3-b880ab477e0b)

**Comment by stufraser1** [comment] 2023-09-06 05:51
This now looks good. Can close I think

**Comment by radix0000** [comment] 2023-09-06 13:09
Current minimalist header has "Risk Data Library Standard", "RDLS" and "Convert and validate ..." tagline once each. Can easily add more words if needed, though.

Closing as done but reopen if you disagree.

**Closed as completed by radix0000** 2023-09-06 13:09 UTC
Labels: must have
